title:  Brandon Burzon
tagline:  A programmer's learning journey
author: 
  name: 'Brandon Burzon'
  twitter:  brandonburzon

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-103649042-1'

menu:
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'About', url: 'about.html'}

social:
- {icon: 'github', link: 'https://www.github.com/brburzon'}
- {icon: 'twitter', link: 'https://twitter.com/brandonburzon'}
- {icon: 'instagram', link: 'https://instagram.com/brburzon'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/brburzon/'}
- {icon: 'envelope', link: 'mailto:brburzon@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
